name = "Grobill Magic Hardtimes"
author = "Mich"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54b4d6fec93196304ed5ddd3173d872ccb9ea8f46f29723645ee220f2793a75e"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
