name = "Grobill Magic Hardtimes"
author = "Mich"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce2dcb3bb79caa8e8195b9999d32402e2285e86dfd94c899e2822da0913b8118"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
