name = "Grobill Magic Hardtimes"
author = "Mich"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1cc880c6b2852e4917f33338e04d43fcb8f9162c7702d8340ddac499d4d3469"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
